/*from:- https://sangbui.com/database-testing-with-java/
also refer to https://www.seleniumeasy.com/selenium-tutorials/database-testing-example-with-selenium-using-java*/
CREATE DATABASE testDB;
USE testDB;
 
CREATE TABLE CUSTOMERS(
   ID   INT              NOT NULL,
   NAME VARCHAR (20)     NOT NULL,
   LICENSE_PLATE  VARCHAR(20)              NOT NULL,
   PIN_CODE  INT         NOT NULL,      
   PRIMARY KEY (ID)
);
 
 
INSERT INTO CUSTOMERS (ID,NAME,LICENSE_PLATE,PIN_CODE) VALUES (1, 'Ramesh', 'BVW 007', 3256);
 
INSERT INTO CUSTOMERS (ID,NAME,LICENSE_PLATE,PIN_CODE) VALUES (2, 'John', 'BAW 207', 5682);
 
INSERT INTO CUSTOMERS (ID,NAME,LICENSE_PLATE,PIN_CODE) VALUES (3, 'Jason', 'CDE 540', 5934);
 
INSERT INTO CUSTOMERS (ID,NAME,LICENSE_PLATE,PIN_CODE) VALUES (4, 'Jake', 'AES 211', 8902);
 
INSERT INTO CUSTOMERS (ID,NAME,LICENSE_PLATE,PIN_CODE) VALUES (5, 'Karl', 'DES 308', 6689);
 
INSERT INTO CUSTOMERS (ID,NAME,LICENSE_PLATE,PIN_CODE) VALUES (6, 'Dion', 'ADE 712', 9812);
 
SELECT * FROM CUSTOMERS;